# HoneyHive semantic conventions — weaver build harness.
#
# Targets:
#   install       download + extract the pinned weaver CLI into ./bin/
#   bundle        install Jekyll dependencies into vendor/bundle
#   check         validate the registry
#   build         render markdown into ./dist/ (weaver) AND build the
#                 branded HTML site into ./_site/ (jekyll)
#   build-md      render markdown into ./dist/ only (skip jekyll)
#   serve         live-preview the HTML site at http://localhost:$(PORT)
#                 (rebuilds markdown first, then jekyll serve --watch)
#   update-docs   inject snippets into hand-authored docs in $(DOCS_DIR)
#   stats         print attribute counts (text format)
#   clean         remove generated artifacts
#
# This wires up the same two-step generation OTel uses for
# https://opentelemetry.io/docs/specs/semconv/:
#   - `make build`        → registry generate (full attribute reference)
#   - `make update-docs`  → registry update-markdown (snippet injection
#                            into curated narrative pages)
# Both share the vendored templates under templates/markdown/.
#
# After weaver renders dist/, Jekyll wraps each page in the branded
# layout under _layouts/default.html and emits the deployable site at
# _site/. HHAI-5108's deploy workflow uploads _site/.

WEAVER       := ./bin/weaver
REGISTRY_DIR := model
TEMPLATES    := templates
DIST         := dist
SITE         := _site
DOCS_DIR     := docs
PORT         := 4000
JEKYLL       := bundle exec jekyll

.PHONY: install bundle check build build-md serve update-docs stats clean help

help:
	@echo "Targets: install | bundle | check | build | build-md | serve | update-docs | stats | clean"

install:
	bash ./install.sh

$(WEAVER):
	bash ./install.sh

# Idempotent — `bundle install` is a no-op once vendor/bundle exists.
# We default to a vendored install so the Ruby toolchain doesn't pollute
# system gems.
bundle:
	bundle config set --local path 'vendor/bundle'
	bundle install --quiet

check: $(WEAVER)
	$(WEAVER) registry check --registry $(REGISTRY_DIR) --future

build-md: $(WEAVER) check
	mkdir -p $(DIST)
	$(WEAVER) registry generate \
		--registry $(REGISTRY_DIR) \
		--templates $(TEMPLATES) \
		markdown \
		$(DIST)
	@echo "rendered markdown → $(DIST)/"

# Full site build: markdown via weaver, HTML via Jekyll.
build: build-md bundle
	$(JEKYLL) build --quiet
	@echo "built HTML site → $(SITE)/  (entry point: $(SITE)/index.html)"

# Preview the branded site at http://localhost:$(PORT)/. Re-runs weaver
# first so changes to model/ or templates/ show up; jekyll itself
# watches files in _layouts/, _includes/, and assets/.
serve: build-md bundle
	@echo "serving HTML site on http://localhost:$(PORT)/  (Ctrl-C to stop)"
	$(JEKYLL) serve --port $(PORT) --livereload

# Inject snippets into hand-authored markdown in $(DOCS_DIR). Each marked
# region (`<!-- semconv <group_id> -->` … `<!-- END AUTOGENERATED TEXT -->`)
# is regenerated from the registry via templates/markdown/snippet.md.j2.
update-docs: $(WEAVER) check
	@if [ ! -d "$(DOCS_DIR)" ]; then \
		echo "no $(DOCS_DIR)/ directory — create it with marked-up markdown first"; \
		exit 1; \
	fi
	$(WEAVER) registry update-markdown \
		--registry $(REGISTRY_DIR) \
		--templates $(TEMPLATES) \
		--target markdown \
		$(DOCS_DIR)
	@echo "updated snippets in $(DOCS_DIR)/"

stats: $(WEAVER)
	$(WEAVER) registry stats --registry $(REGISTRY_DIR)

clean:
	rm -rf $(DIST) $(SITE) .jekyll-cache .jekyll-metadata
