# HoneyHive semantic conventions — weaver build harness.
#
# Targets:
#   install      download + extract the pinned weaver CLI into ./bin/
#   check        validate the registry
#   build        render the attribute reference site into ./dist/
#   serve        serve ./dist/ on http://localhost:$(PORT) (markdown only)
#   update-docs  inject snippets into hand-authored docs in $(DOCS_DIR)
#   stats        print attribute counts (text format)
#   clean        remove generated artifacts
#
# This wires up the same two-step generation OTel uses for
# https://opentelemetry.io/docs/specs/semconv/:
#   - `make build`        → registry generate (full attribute reference)
#   - `make update-docs`  → registry update-markdown (snippet injection
#                            into curated narrative pages)
# Both share the vendored templates under templates/markdown/.

WEAVER       := ./bin/weaver
REGISTRY_DIR := model
TEMPLATES    := templates
DIST         := dist
DOCS_DIR     := docs
PORT         := 8765

.PHONY: install check build serve update-docs stats clean help

help:
	@echo "Targets: install | check | build | serve | update-docs | stats | clean"

install:
	bash ./install.sh

$(WEAVER):
	bash ./install.sh

check: $(WEAVER)
	$(WEAVER) registry check --registry $(REGISTRY_DIR) --future

build: $(WEAVER) check
	mkdir -p $(DIST)
	$(WEAVER) registry generate \
		--registry $(REGISTRY_DIR) \
		--templates $(TEMPLATES) \
		markdown \
		$(DIST)
	@echo "built $(DIST)/"

# Browse the generated reference at http://localhost:$(PORT)/.
# Note: this serves raw markdown — for HTML rendering, point a Mintlify or
# Hugo dev server at $(DIST), or use a markdown previewer (glow, grip).
serve: build
	@echo "serving $(DIST)/ on http://localhost:$(PORT)/  (Ctrl-C to stop)"
	@cd $(DIST) && python3 -m http.server $(PORT)

# Inject snippets into hand-authored markdown in $(DOCS_DIR). Each marked
# region (`<!-- semconv <group_id> -->` … `<!-- END AUTOGENERATED TEXT -->`)
# is regenerated from the registry via templates/markdown/snippet.md.j2.
update-docs: $(WEAVER) check
	@if [ ! -d "$(DOCS_DIR)" ]; then \
		echo "no $(DOCS_DIR)/ directory — create it with marked-up markdown first"; \
		exit 1; \
	fi
	$(WEAVER) registry update-markdown \
		--registry $(REGISTRY_DIR) \
		--templates $(TEMPLATES) \
		--target markdown \
		$(DOCS_DIR)
	@echo "updated snippets in $(DOCS_DIR)/"

stats: $(WEAVER)
	$(WEAVER) registry stats --registry $(REGISTRY_DIR)

clean:
	rm -rf $(DIST)
