import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';

const DIST_DIR = './dist';
const DOCS_SRC_DIR = './docs-src';
const REGISTRY_DIR = join(DOCS_SRC_DIR, 'registry');

interface NamespaceFile {
  path: string;
  namespace: string;
  title: string;
}

function titleCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
}

function extractNamespace(filename: string): string {
  return filename.replace(/\.md$/, '');
}

function addVitepressHeader(content: string, namespace: string): string {
  const title = titleCase(namespace);

  // Strip Hugo-style frontmatter comment if present
  let cleanContent = content.replace(
    /<!-- NOTE: THIS FILE IS AUTOGENERATED\. DO NOT EDIT BY HAND\. -->\n<!-- see templates\/registry\/markdown\/.*? -->\n/,
    ''
  );

  // Add VitePress YAML frontmatter if not already present
  if (!cleanContent.startsWith('---')) {
    const frontmatter = `---
title: '${title}'
outline: deep
---

<!-- Auto-generated. Do not edit. Run \`pnpm generate:docs\` to regenerate. -->

`;
    cleanContent = frontmatter + cleanContent;
  }

  return cleanContent;
}

function processAttributeFiles(): NamespaceFile[] {
  const attributesDir = join(DIST_DIR, 'attributes');
  const targetDir = join(REGISTRY_DIR, 'attributes');

  // Create target directory if it doesn't exist
  mkdirSync(targetDir, { recursive: true });

  const files: NamespaceFile[] = [];

  if (!existsSync(attributesDir)) {
    console.log('No attributes directory found in dist/');
    return files;
  }

  const attributeFiles = readdirSync(attributesDir).filter((f) => f.endsWith('.md') && f !== 'README.md');

  for (const file of attributeFiles) {
    const sourcePath = join(attributesDir, file);
    const content = readFileSync(sourcePath, 'utf-8');
    const namespace = extractNamespace(file);
    const title = titleCase(namespace);

    // Add VitePress frontmatter
    const processedContent = addVitepressHeader(content, namespace);

    // Write to target location
    const targetPath = join(targetDir, file);
    writeFileSync(targetPath, processedContent, 'utf-8');

    files.push({
      path: targetPath,
      namespace,
      title,
    });

    console.log(`✓ Processed ${file}`);
  }

  return files;
}

function processEntityFiles(): NamespaceFile[] {
  const entitiesDir = join(DIST_DIR, 'entities');
  const targetDir = join(REGISTRY_DIR, 'entities');

  const files: NamespaceFile[] = [];

  if (!existsSync(entitiesDir)) {
    console.log('No entities directory found in dist/');
    return files;
  }

  // Create target directory if it doesn't exist
  mkdirSync(targetDir, { recursive: true });

  const entityFiles = readdirSync(entitiesDir).filter((f) => f.endsWith('.md') && f !== 'README.md');

  for (const file of entityFiles) {
    const sourcePath = join(entitiesDir, file);
    const content = readFileSync(sourcePath, 'utf-8');
    const namespace = extractNamespace(file);
    const title = titleCase(namespace);

    // Add VitePress frontmatter
    const processedContent = addVitepressHeader(content, namespace);

    // Write to target location
    const targetPath = join(targetDir, file);
    writeFileSync(targetPath, processedContent, 'utf-8');

    files.push({
      path: targetPath,
      namespace,
      title,
    });

    console.log(`✓ Processed ${file}`);
  }

  return files;
}

function generateSidebar(attributeFiles: NamespaceFile[], entityFiles: NamespaceFile[]): void {
  const items = [];

  // Add overview
  items.push({ text: 'Overview', link: '/registry/' });

  // Add attribute namespace links
  for (const file of attributeFiles) {
    items.push({
      text: file.title,
      link: `/registry/attributes/${file.namespace}`,
    });
  }

  // Add entity namespace links (if any)
  for (const file of entityFiles) {
    items.push({
      text: file.title,
      link: `/registry/entities/${file.namespace}`,
    });
  }

  const sidebarContent = `export const referenceSidebar = [
  {
    text: 'Reference',
    items: [
${items.map((item) => `      { text: '${item.text}', link: '${item.link}' },`).join('\n')}
    ],
  },
];
`;

  const sidebarPath = join(REGISTRY_DIR, '.sidebar.ts');
  mkdirSync(dirname(sidebarPath), { recursive: true });
  writeFileSync(sidebarPath, sidebarContent, 'utf-8');

  console.log(`✓ Generated sidebar at ${sidebarPath}`);
}

function generateIndexPage(attributeFiles: NamespaceFile[], entityFiles: NamespaceFile[]): void {
  const registryDir = join(DOCS_SRC_DIR, 'registry');
  const indexPath = join(registryDir, 'index.md');

  // Only generate if it doesn't already exist
  if (existsSync(indexPath)) {
    console.log(`index.md already exists, skipping generation`);
    return;
  }

  const namespaces = [
    ...attributeFiles.map((f) => ({ title: f.title, link: `/registry/attributes/${f.namespace}` })),
    ...entityFiles.map((f) => ({ title: f.title, link: `/registry/entities/${f.namespace}` })),
  ];

  const indexContent = `---
title: Registry
outline: false
---

# Semantic Conventions Registry

Browse the canonical attribute schema for HoneyHive AI observability.

## Namespaces

${namespaces.map((ns) => `- [${ns.title}](${ns.link})`).join('\n')}
`;

  mkdirSync(dirname(indexPath), { recursive: true });
  writeFileSync(indexPath, indexContent, 'utf-8');

  console.log(`✓ Generated index at ${indexPath}`);
}

function main(): void {
  try {
    console.log('Postprocessing weaver markdown for VitePress...');

    // Ensure dist was generated
    if (!existsSync(DIST_DIR)) {
      throw new Error(`Expected ${DIST_DIR} directory. Run 'make build' first.`);
    }

    // Process attribute and entity files
    const attributeFiles = processAttributeFiles();
    const entityFiles = processEntityFiles();

    if (attributeFiles.length === 0 && entityFiles.length === 0) {
      throw new Error('No markdown files generated by weaver.');
    }

    // Generate sidebar and index
    generateSidebar(attributeFiles, entityFiles);
    generateIndexPage(attributeFiles, entityFiles);

    console.log('✓ Postprocessing complete');
  } catch (error) {
    console.error('Error:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

main();
